# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "ci-cd" ]
  pull_request:
    branches: [ "ci-cd" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./AdvancedTests.ECommerce/

    - name: Build solution
      run: dotnet build ./AdvancedTests.ECommerce/ --no-restore --configuration Release

    - name: Test
      run: dotnet test ./AdvancedTests.ECommerce/ --no-build --configuration Release --logger trx

    - name: Install Stryker
      run: dotnet tool install -g dotnet-stryker

    - name: Run Stryker
      run: dotnet-stryker
      working-directory: ./AdvancedTests.ECommerce/AdvancedTests.ECommerce.UnitTests/

    - name: Deploy
      run: echo "Deploying..."
